export const Categories = {

  // vsetky vlastnosti ktore sa daju pouzit na generovanie kategorii
  // ALL_FEATURES:{
  //   id: true,
  //   id_category: true,
  //   name: true,
  //   place: true,
  //   short_name: true,
  //   author: true,
  //   organizer: true,
  //   files: true,
  //   date_from: true,
  //   date_to: true,
  //   note: true,
  //   year_of_publication: true,
  //   editor_ship: true,
  //   issue_number: true,
  //   literature_type: true,
  //   visited: true,
  //   presented: true,
  //   expenses: true,
  // },

  Projects:{
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    author: true,
    files: true,
    date_from: true,
    date_to: true,
    note: true,
    expenses: true,
  },

  Publications:{
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    author: true,
    files: true,
    note: true,
    year_of_publication: true,
    editor_ship: true,
    issue_number: true,
  },

  Reports:{
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    author: true,
    files: true,
    note: true,
  },

  Books : {
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    author: true,
    editorship: true,
    issue_number: true,
    year_of_publication: true,
    literature_type: true,
    files: true,
    note: true,
  },

  Events:{
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    place: true,
    organizer: true,
    files: true,
    visited: true,
    presented: true,
    date_from: true,
    date_to: true,
    note: true,
    expenses: true,
  },

  Contacts : {
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    place: true,
    organizer: true,
    author: true,
    visited: true,
    presented: true,
    files: true,
    date_from: true,
    date_to: true,
    note: true,
  },

  Registry : {
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    files: true,
    note: true,
    expenses: true,
  },

  Software : {
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    files: true,
    note: true,
    expenses: true,

  },

  Notebook : {
    id: true,
    id_category: true,
    name: true,
    short_name: true,
    files: true,
    note: true,
    expenses: true,
    place: true,
    organizer: true,
    author: true,
  },


}
